import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame} from 'remotion';

const purple='#6d12ff'; const ink='#111'; const gray='#666';
const pill={borderRadius:999, padding:'15px 24px', border:'1px solid #ddd', fontSize:17, background:'#fff'} as React.CSSProperties;
const Card=({num,title,body,link}:{num:string,title:string,body:string,link:string})=><div style={{borderTop:'1px solid #d8d8d8',padding:'28px 0 36px',display:'grid',gridTemplateColumns:'100px 1.1fr 1fr',gap:20}}><div style={{fontFamily:'monospace',color:purple,fontSize:16}}>{num}</div><h3 style={{fontSize:38,letterSpacing:'-.05em',margin:0,fontWeight:500}}>{title}</h3><div style={{fontSize:18,lineHeight:1.45,color:gray}}><p style={{margin:'0 0 26px'}}>{body}</p><span style={{color:ink}}>{link} →</span></div></div>;
export default function DesignMe(){
 const f=useCurrentFrame(); const enter=spring({frame:f,fps:24,config:{damping:18,stiffness:80}}); const scroll=interpolate(f,[0,150,350,700,1080],[0,0,780,1550,2150],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
 return <AbsoluteFill style={{background:'#fff',color:ink,fontFamily:'Arial, Helvetica, sans-serif',overflow:'hidden'}}>
  <div style={{position:'absolute',inset:0,transform:`translateY(${-scroll}px)`}}>
   <header style={{height:92,padding:'0 64px',display:'flex',alignItems:'center',justifyContent:'space-between',borderBottom:'1px solid #eee',background:'#fff'}}><b style={{fontSize:27,letterSpacing:'-.08em'}}>design<span style={{color:purple}}>me</span></b><nav style={{display:'flex',gap:34,fontSize:15}}><span>Services</span><span>Our work</span><span>Company</span><span>Insights</span><button style={{...pill,background:ink,color:'#fff',border:0,padding:'12px 20px'}}>Book a call ↗</button></nav></header>
   <section style={{minHeight:840,padding:'82px 64px 60px',display:'flex',flexDirection:'column',justifyContent:'space-between',background:'linear-gradient(125deg,#faf8ff,#fff 55%)'}}><div style={{maxWidth:1200,opacity:enter,transform:`translateY(${30*(1-enter)}px)`}}><div style={{fontSize:15,color:purple,letterSpacing:'.12em',textTransform:'uppercase',marginBottom:38}}>Brand, product & website design</div><h1 style={{fontSize:112,lineHeight:.94,letterSpacing:'-.08em',fontWeight:500,maxWidth:1000,margin:0}}>Look like the<br/><em style={{color:purple,fontStyle:'normal'}}>company</em> you’re becoming.</h1><p style={{fontSize:25,lineHeight:1.25,maxWidth:650,margin:'40px 0'}}>Design that turns attention into revenue. We help tech startups, enterprises, and product teams shape beautiful brands, products, and launch experiences.</p><div style={{display:'flex',gap:14}}><button style={{...pill,background:purple,color:'#fff',border:0}}>Book a call ↗</button><button style={pill}>Our services ↓</button></div></div><div style={{fontSize:15,color:gray}}>Trusted by 100+ startups worldwide <span style={{marginLeft:45,color:ink}}>N3XT.io　 Lightdash　 seamless.ai　 Ballogy　 ◇</span></div></section>
   <section style={{padding:'100px 64px 120px',background:'#f5f5f5'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginBottom:50}}><div><div style={{color:purple,fontFamily:'monospace',marginBottom:24}}>HOW WE HELP</div><h2 style={{fontSize:72,letterSpacing:'-.07em',fontWeight:500,lineHeight:.95,margin:0}}>Support for<br/>every stage.</h2></div><p style={{maxWidth:380,fontSize:19,lineHeight:1.4,color:gray}}>Bring us in when your idea, product, website, or brand needs to feel sharper, clearer, and ready for what comes next.</p></div><Card num="01" title="Brand Identity" body="A system that makes every touchpoint look like the same company built it. Logo, visual identity, strategy, naming, and everything in between." link="Explore our branding process"/><Card num="02" title="Websites" body="Designed and built by one team. From first launches to full rebrands and replatforms, we ship sites that are ready to perform." link="Explore our website process"/><Card num="03" title="Product Design" body="We sit inside your workflow, work with your engineers, and ship interfaces that are dev-ready on delivery." link="Explore our product process"/><Card num="04" title="Motion & Video" body="The stuff that stops the scroll and sells the product before anyone reads a word." link="Help me with a launch video"/></section>
   <section style={{padding:'120px 64px',background:ink,color:'#fff',minHeight:760}}><div style={{color:'#a985ff',fontFamily:'monospace',marginBottom:28}}>SELECTED WORK</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'end'}}><h2 style={{fontSize:82,lineHeight:.92,letterSpacing:'-.08em',fontWeight:500,margin:0}}>Case<br/>studies.</h2><p style={{maxWidth:400,fontSize:22,lineHeight:1.3,color:'#bbb'}}>From funded startups to $1B unicorns, we make digital products people want to use.</p></div><div style={{marginTop:70,height:300,borderRadius:28,background:'linear-gradient(135deg,#7848ff,#c2b5ff 55%,#f4e4d1)',display:'flex',alignItems:'center',padding:50}}><div><div style={{fontSize:18,opacity:.7}}>Ballogy · Product design</div><div style={{fontSize:54,letterSpacing:'-.06em',marginTop:12}}>Built for the next<br/>generation of athletes.</div></div></div></section>
   <footer style={{padding:'100px 64px 50px',background:'#fff'}}><div style={{fontSize:76,letterSpacing:'-.08em',lineHeight:.9}}>Ready to look like<br/><span style={{color:purple}}>what’s next?</span></div><button style={{...pill,background:ink,color:'#fff',marginTop:45}}>Book a call ↗</button><div style={{borderTop:'1px solid #ddd',marginTop:120,paddingTop:24,color:gray,display:'flex',justifyContent:'space-between'}}>© DesignMe　 Gdansk · NYC <span>Instagram　LinkedIn</span></div></footer>
  </div>
 </AbsoluteFill>;
}